ng generate component admin/dashboard
ng generate component admin/detail-order
ng generate component admin/header
ng generate component admin/footer
ng generate component admin/index
ng generate component admin/kategori-pos
ng generate component admin/left-sidebar
ng generate component admin/login
ng generate component admin/logout
ng generate component admin/manage_orders
ng generate component admin/manage_products
ng generate component admin/order
ng generate component admin/pelanggan
ng generate component admin/pembayaran
ng generate component admin/pos
ng generate component admin/produk
ng generate component admin/tambah-kategori
ng generate component admin/tambah-pos
ng generate component admin/tambah-produk
ng generate component admin/topbar
ng generate component admin/ubah-pos
ng generate component admin/ubah-produk
