ng generate component about
ng generate component blog
ng generate component cart
ng generate component checkout
ng generate component contact
ng generate component cost
ng generate component detail-blog
ng generate component detail-produk
ng generate component gallery
ng generate component konfirmasi-barang
ng generate component konfirmasi-pembayaran
ng generate component login
ng generate component logout
ng generate component signup
ng generate component nota-order
ng generate component orderan
ng generate component pembayaran
ng generate component rincian-produk
ng generate component shop
